action.yml

Use ${{ github.action_path }} to get the python file correctly on other repos

Fix python script path

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/doc.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml
.github/pull_request_template.md

#34 added a few issue templates and a pull request template.

chore: Adding issue and pull request templates

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

For the readme file, I have made a refactor based on the [custom Icon Badges](https://github.com/DenverCoder1/custom-icon-badges) project to avoid repetition.
fixes #34

chore: add code of conduct and contribution guidelines file

---

api/index.py
api/validate.py
tests/test_validate.py
tox.ini

refactor: Removed 'required' attributes and simplify validation

---

api/__init__.py
tests/conftest.py
tests/test_app.py

ci: Add test cases for rendering the cards

---

tests/conftest.py
tests/test_validate.py

Refactored test_validate.py with pytest.fixture

refactor: Use pytest fixtures for mock request

---

action.py
tests/test_action.py

ci: Add unit tests for parse_videos and FileUpdater

---

api/locale/id.yml

feat: Added Indonesian Translations to YouTube Cards

---

pyproject.toml

chore: Bump version to 1.3.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/doc.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml

* Added emoji key in titles
* Modified template descriptions
* Added questions to answer in textarea descriptions
* Removed screenshot field from docs, feature, question

chore: Improvements to issue templates

---

action.yml
requirements-action.txt
requirements.txt

* Install requirements in GitHub action using requirements-action.yml instead of a separately maintained list.
* Removed orjson from action deps
* Set fixed (==) versions in requirements.txt for Flask, orjson

chore(deps): Use requirements file in action.yml and fixed deps

---

api/locale/hi.yml

This PR adds hindi translations to the `api/locale` folder, using the `hi` identifier.

feat: Added Hindi translations

---

api/locale/fa.yml

feat: Added Persian (Farsi) translations

---

api/locale/ur.yml

I've added Urdu translations according to Issue #48 
Haven't tested since I edited directly from Github but I'm pretty sure it'll work since its simple urdu text.

Added urdu translation

---

api/locale/ba.yml
api/locale/bn.yml

Bangla Translation added
Issue => #48

feat: Added Bengali translations

---

api/locale/ja.yml

Added Japanese translations
References #48

feat: Added Japanese translations

---

.pre-commit-config.yaml
tests/test_utils.py

Remove unused imports on commit with autoflake

ci: Remove unused imports with autoflake

---

.github/workflows/youtube-cards.yml

Sets the example workflow to use HTML since the current theme context displays twice on the GitHub Actions Marketplace

chore: Set example workflow to use HTML

---

api/templates/index.html

Use relative links for examples on the demo site for ease of testing locally and on test builds.

fix(demo): Use active domain for examples for ease of testing

---

api/index.py
api/templates/error.svg
api/templates/main.svg
tests/test_app.py

Fixes #69 
Also fixes rtl text in browsers that do not support CSS through SVGs.

fix: Adjust alignment of image within rectangle

---

README.md

docs(readme): Updated table and links and added an example

---

api/locale/it.yml

feat: Added Italian Translations

---

README.md

docs(readme): Set token permissions in examples

---

README.md
action.yml

feat: Add committed, pushed, and sha outputs

---

api/locale/pt.yml

feat: Added Portuguese translations

---

api/locale/es.yml

Spanish translation
- Spanish translation

feat: Added Spanish translations

---

README.md
action.py
action.yml
api/index.py
api/templates/index.html
api/templates/main.svg
tests/test_action.py
tests/test_app.py

Fixes #26 
`border_radius=0`
`border_radius=25`
`border_radius=5` (default)

feat: Add support for setting the border radius

---

.github/workflows/youtube-cards.yml
README.md
action.py
action.yml
api/index.py
api/templates/index.html
api/templates/main.svg
api/utils.py
tests/test_action.py
tests/test_app.py
tests/test_utils.py

feat: Support multiple lines for titles with `max_title_lines`

---

README.md

docs(readme): Add footnote about locales

---

api/locale/de.yml

Added German translations
References #48

feat: Add German translations

---

api/locale/mi.yml

Added Maori translations
References #48

feat: Add Maori translations

---

api/index.py
api/templates/main.svg
api/utils.py
tests/test_app.py

resolves #131 
This PR adds support for RTL languages in the youtube card title text.

feat: Support RTL language titles

---

api/locale/ko.yml

feat: Add Korean translations

---

.github/workflows/pre-commit.yml
.github/workflows/python-lint.yml
.github/workflows/python-test.yml
action.yml
pyproject.toml
tox.ini

fix: Update Python and fix wheels by adding build target

---

api/index.py
api/templates/error.svg
api/templates/main.svg

I am running low on remaining bandwidth on my Vercel plan so disabling Roboto for now to save bandwidth

perf: Add flag in Python to reduce bandwith usage

---

README.md

docs(readme): Add link to playlist id wiki page
